networks:
  t2c:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.112.0/24
          gateway: 172.16.112.1

services:

  t2c-postgresql:
    image: postgres:18.4-alpine
    container_name: t2c-postgresql
    hostname: t2c-postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DATABASE_USER:-t2c_user}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-root}
      - POSTGRES_DB=${DATABASE_NAME:-t2c_master}
    volumes:
      - t2c_postgresql_data:/var/lib/postgresql
    networks:
      - t2c

  t2c-rabbitmq:
    image: rabbitmq:4.3-management-alpine
    container_name: t2c-rabbitmq
    hostname: t2c-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-user}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-root}
    volumes:
      - t2c_rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq/permit-deprecated.conf:/etc/rabbitmq/conf.d/10-permit-deprecated.conf:ro
    networks:
      - t2c

volumes:
  t2c_postgresql_data:
  t2c_rabbitmq_data: