networks:
  t2c:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.112.0/24
          gateway: 172.16.112.1

services:

  t2c-postgresql:
    image: postgres:18.4-alpine
    container_name: t2c-postgresql
    hostname: t2c-postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DATABASE_USER:-t2c_user}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-root}
      - POSTGRES_DB=${DATABASE_NAME:-t2c_master}
    volumes:
      - t2c_postgresql_data:/var/lib/postgresql
    networks:
      - t2c

volumes:
  t2c_postgresql_data:
