networks:
  t2c:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.112.0/24
          gateway: 172.16.112.1

services:

  t2c-postgresql:
    image: postgres:18.4-alpine
    container_name: t2c-postgresql
    hostname: t2c-postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DATABASE_USER:-t2c_user}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-root}
      - POSTGRES_DB=${DATABASE_NAME:-t2c_master}
    volumes:
      - t2c_postgresql_data:/var/lib/postgresql
    networks:
      - t2c

  t2c-redis:
    image: redis:8.2-alpine
    container_name: t2c-redis
    hostname: t2c-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD:-root}"]
    volumes:
      - t2c_redis_data:/data
    networks:
      - t2c

volumes:
  t2c_postgresql_data:
  t2c_redis_data:
