[project]
name = "t2c_backend"
version = "0.1.0"
description = "Open source t2c backend base"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asgi-correlation-id>=4.3.4",
    "fastapi-pagination>=0.15.6",
    "fastapi[all]>=0.128.0",
    "gunicorn>=23.0.0",
    "loguru>=0.7.3",
    "pyjwt>=2.10.1",
    "sqlalchemy[asyncio]>=2.0.45",
    "tomlkit>=0.14.0",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]

[dependency-groups]
dev = [
    "alembic==1.17.0",
    "asyncpg>=0.31.0",
    "ruff>=0.14.13",
]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["I", "N", "A", "UP", "F", "E", "T20"]
