"""update

Revision ID: 5099d557d82a
Revises: 1a386f695ecb
Create Date: 2026-01-22 16:13:29.786642

"""

from collections.abc import Sequence

import sqlalchemy as sa

import t2c_backend
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5099d557d82a"
down_revision: str | Sequence[str] | None = "1a386f695ecb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asset_type_category_group",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("order", sa.Numeric(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "typeplate_images",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("image", t2c_backend.core.db.types.ImageType(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "asset_type_categories",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("has_typeplates", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "user_id", name="_asset_type_category_name_unique"),
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("released", "pending", "rejected", name="documentstatus"),
            nullable=True,
        ),
        sa.Column(
            "type",
            sa.Enum(
                "instruction_manual",
                "inspection",
                "typeplate",
                "declaration_file",
                name="documenttype",
            ),
            nullable=False,
        ),
        sa.Column("content_type", sa.Text(), nullable=False),
        sa.Column("location_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "name", "type", "location_id", name="_name_type_location_location_id_unique"
        ),
    )
    op.create_table(
        "asset_type_category_fields",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "field_type",
            sa.Enum(
                "time",
                "url",
                "text",
                "radio",
                "password",
                "number",
                "image",
                "file",
                "email",
                "date",
                "datetime",
                "checkbox",
                "multiselect",
                "select",
                name="inputtype",
            ),
            nullable=False,
        ),
        sa.Column("field_name", sa.Text(), nullable=False),
        sa.Column("field_place_holder", sa.Text(), nullable=True),
        sa.Column("field_display_name", sa.Text(), nullable=False),
        sa.Column("field_is_required", sa.Boolean(), nullable=False),
        sa.Column("field_order", sa.Numeric(), nullable=False),
        sa.Column("asset_type_category_id", sa.BigInteger(), nullable=False),
        sa.Column("asset_type_category_group_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_type_category_group_id"], ["asset_type_category_group.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["asset_type_category_id"], ["asset_type_categories.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "asset_type_category_id", "field_name", name="_unique_field_name_per_category"
        ),
        sa.UniqueConstraint(
            "asset_type_category_id", "field_order", name="_unique_field_order_per_category"
        ),
    )
    op.create_table(
        "asset_types",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("video_links", sa.Text(), nullable=True),
        sa.Column("video_title", sa.Text(), nullable=True),
        sa.Column("web_link", sa.Text(), nullable=True),
        sa.Column("web_link_title", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("weight", sa.Numeric(), nullable=True),
        sa.Column("manufacturer", sa.Text(), nullable=True),
        sa.Column("asset_type_category_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_type_category_id"], ["asset_type_categories.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "asset_type_category_field_options",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("option_id", sa.Text(), nullable=False),
        sa.Column("option_label", sa.Text(), nullable=False),
        sa.Column("asset_field_type_category_field_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_field_type_category_field_id"],
            ["asset_type_category_fields.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "option_id",
            "asset_field_type_category_field_id",
            name="_asset_field_type_category_field_option_unique",
        ),
    )
    op.create_table(
        "asset_type_fields",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("field_id", sa.BigInteger(), nullable=False),
        sa.Column("response_value", sa.Text(), nullable=True),
        sa.Column("asset_type_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["asset_type_id"], ["asset_types.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["field_id"], ["asset_type_category_fields.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "asset_types_documents",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("content_type", sa.Text(), nullable=False),
        sa.Column("asset_type_id", sa.BigInteger(), nullable=False),
        sa.Column("location_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["asset_type_id"], ["asset_types.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "asset_type_id", name="_name_asset_type_asset_type_id_unique"),
    )
    op.create_table(
        "typeplates",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("test_results", sa.Text(), nullable=True),
        sa.Column("eu_id", sa.Text(), nullable=True),
        sa.Column("eu_file_id", sa.Uuid(), nullable=True),
        sa.Column("carbon_footprint_label", sa.Text(), nullable=True),
        sa.Column("asset_type_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["asset_type_id"], ["asset_types.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["eu_file_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "asset_type_field_options",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("option_id", sa.BigInteger(), nullable=False),
        sa.Column("asset_type_field_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_type_field_id"], ["asset_type_fields.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["option_id"], ["asset_type_category_field_options.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "typelate_image_mapping",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("typeplate_id", sa.BigInteger(), nullable=False),
        sa.Column("typeplate_image_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["typeplate_id"], ["typeplates.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["typeplate_image_id"], ["typeplate_images.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "typeplate_documents",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("typeplate_id", sa.BigInteger(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["typeplate_id"], ["typeplates.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("typeplate_documents")
    op.drop_table("typelate_image_mapping")
    op.drop_table("asset_type_field_options")
    op.drop_table("typeplates")
    op.drop_table("asset_types_documents")
    op.drop_table("asset_type_fields")
    op.drop_table("asset_type_category_field_options")
    op.drop_table("asset_types")
    op.drop_table("asset_type_category_fields")
    op.drop_table("documents")
    op.drop_table("asset_type_categories")
    op.drop_table("typeplate_images")
    op.drop_table("asset_type_category_group")
    # ### end Alembic commands ###
