"""update

Revision ID: 75e89f6cc4a2
Revises: f3d11e8e0535
Create Date: 2026-01-23 12:15:05.289072

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "75e89f6cc4a2"
down_revision: str | Sequence[str] | None = "f3d11e8e0535"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("pass_id", sa.Text(), nullable=False),
        sa.Column("device_id", sa.Text(), nullable=False),
        sa.Column("manufacturing_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "putting_into_service",
                "placing_on_the_market",
                "making_available_on_the_market",
                "re_use",
                "repair",
                "maintenance",
                "remanufacturing",
                "repurposing",
                "treatment",
                "preparation_for_re_use",
                "preparation_for_repurposing",
                "preparation_for_recycling",
                "recycling",
                "waste_management",
                name="assetstatus",
            ),
            nullable=False,
        ),
        sa.Column("serial_no", sa.Text(), nullable=True),
        sa.Column("economic_operator", sa.Text(), nullable=True),
        sa.Column("asset_type_id", sa.BigInteger(), nullable=False),
        sa.Column("location_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["asset_type_id"], ["asset_types.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "location_id", name="_unique_device_id_location_id"),
    )
    op.create_table(
        "asset_monitoring_history",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("device_id", sa.Text(), nullable=False),
        sa.Column("asset_id", sa.BigInteger(), nullable=True),
        sa.Column("monitoring_data", sa.JSON(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("insert_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "audits",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("inspection_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.Date(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("asset_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "services",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("contact", sa.Text(), nullable=True),
        sa.Column("expire_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("service_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("web", sa.Text(), nullable=True),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("service_type", sa.Enum("premium", "basic", name="servicetypes"), nullable=False),
        sa.Column("asset_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "audit_tasks",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("task_name", sa.Text(), nullable=False),
        sa.Column("status", sa.Enum("SUCCEEDED", "FAILED", name="audittaskstatus"), nullable=False),
        sa.Column("audit_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(["audit_id"], ["audits.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "audit_task_documents",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("content_type", sa.Text(), nullable=False),
        sa.Column("audit_task_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["audit_task_id"], ["audit_tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "audit_task_id", name="_name_audit_task_audit_task_id_unique"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("audit_task_documents")
    op.drop_table("audit_tasks")
    op.drop_table("services")
    op.drop_table("audits")
    op.drop_table("asset_monitoring_history")
    op.drop_table("assets")
    # ### end Alembic commands ###
