"""update

Revision ID: c74792933b5f
Revises: 75e89f6cc4a2
Create Date: 2026-02-06 19:15:03.060486

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c74792933b5f"
down_revision: str | Sequence[str] | None = "75e89f6cc4a2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_invites",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("location_id", sa.BigInteger(), nullable=False),
        sa.Column("inviter_id", sa.BigInteger(), nullable=False),
        sa.Column("invitee_email", sa.Text(), nullable=False),
        sa.Column("token", sa.Text(), nullable=False),
        sa.Column(
            "status", sa.Enum("pending", "accepted", "rejected", name="status"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["inviter_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_invites_token"), "user_invites", ["token"], unique=True)
    op.create_table(
        "user_invite_roles",
        sa.Column("role_id", sa.BigInteger(), nullable=False),
        sa.Column("invitee_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["invitee_id"], ["user_invites.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("role_id", "invitee_id"),
    )
    op.drop_table("asset_monitoring_history")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asset_monitoring_history",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("asset_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "monitoring_data",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column(
            "insert_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("asset_monitoring_history_asset_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("asset_monitoring_history_pkey")),
    )
    op.drop_table("user_invite_roles")
    op.drop_index(op.f("ix_user_invites_token"), table_name="user_invites")
    op.drop_table("user_invites")
    # ### end Alembic commands ###
