"""reduce_register_field

Revision ID: pkg_0005
Revises: pkg_0004
Create Date: 2026-07-30 14:58:54.973990

Also renames taxonomies -> product_pass_types (and organizations.taxonomy_id ->
product_pass_type_id).

pkg_0001 creates the table under its new name, because the static-data revision (pkg_0002)
seeds it through the ORM model, which now maps product_pass_types. The renames below are
therefore guarded: they are a no-op on a fresh database and only rewrite databases created
before the rename.

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "pkg_0005"
down_revision: str | Sequence[str] | None = "pkg_0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("locations", "street")
    op.drop_column("locations", "mobile_number")
    op.drop_column("locations", "postcode")
    op.drop_column("locations", "name")
    op.drop_column("locations", "email")
    op.drop_column("locations", "tel_number")
    op.drop_column("locations", "fax_number")
    op.drop_column("locations", "region")
    op.alter_column("organizations", "number", existing_type=sa.TEXT(), nullable=True)
    op.drop_column("organizations", "email")
    # ### end Alembic commands ###

    rename_taxonomy_to_product_pass_type()


def rename_taxonomy_to_product_pass_type() -> None:
    """Rename taxonomies -> product_pass_types, no-op if already renamed."""
    op.execute("ALTER TABLE IF EXISTS taxonomies RENAME TO product_pass_types")
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'organizations' AND column_name = 'taxonomy_id'
            ) THEN
                ALTER TABLE organizations RENAME COLUMN taxonomy_id TO product_pass_type_id;
            END IF;
            IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'taxonomies_pkey') THEN
                ALTER INDEX taxonomies_pkey RENAME TO product_pass_types_pkey;
            END IF;
            IF EXISTS (
                SELECT 1 FROM pg_constraint WHERE conname = 'organizations_taxonomy_id_fkey'
            ) THEN
                ALTER TABLE organizations
                    RENAME CONSTRAINT organizations_taxonomy_id_fkey
                    TO organizations_product_pass_type_id_fkey;
            END IF;
        END $$
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conname = 'organizations_product_pass_type_id_fkey'
            ) THEN
                ALTER TABLE organizations
                    RENAME CONSTRAINT organizations_product_pass_type_id_fkey
                    TO organizations_taxonomy_id_fkey;
            END IF;
            IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'product_pass_types_pkey') THEN
                ALTER INDEX product_pass_types_pkey RENAME TO taxonomies_pkey;
            END IF;
            IF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'organizations' AND column_name = 'product_pass_type_id'
            ) THEN
                ALTER TABLE organizations RENAME COLUMN product_pass_type_id TO taxonomy_id;
            END IF;
        END $$
        """
    )
    op.execute("ALTER TABLE IF EXISTS product_pass_types RENAME TO taxonomies")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organizations", sa.Column("email", sa.TEXT(), autoincrement=False, nullable=False)
    )
    op.alter_column("organizations", "number", existing_type=sa.TEXT(), nullable=False)
    op.add_column("locations", sa.Column("region", sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column(
        "locations", sa.Column("fax_number", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "locations", sa.Column("tel_number", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.add_column("locations", sa.Column("email", sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column("locations", sa.Column("name", sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column("locations", sa.Column("postcode", sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column(
        "locations", sa.Column("mobile_number", sa.TEXT(), autoincrement=False, nullable=False)
    )
    op.add_column("locations", sa.Column("street", sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
