"""unique_asset_type_per_category

Revision ID: pkg_0006
Revises: pkg_0005
Create Date: 2026-09-17 12:20:43.688704

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "pkg_0006"
down_revision: str | Sequence[str] | None = "pkg_0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "uq_asset_type_name_per_category",
        "asset_types",
        [
            "asset_type_category_id",
            sa.literal_column("lower(btrim(regexp_replace(name, '\\s+', ' ', 'g')))"),
        ],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_asset_type_name_per_category", table_name="asset_types")
    # ### end Alembic commands ###
