"""reduce_register_field

Revision ID: pkg_0005
Revises: pkg_0004
Create Date: 2026-07-30 14:58:54.973990

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "pkg_0005"
down_revision: str | Sequence[str] | None = "pkg_0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("locations", "street")
    op.drop_column("locations", "mobile_number")
    op.drop_column("locations", "postcode")
    op.drop_column("locations", "name")
    op.drop_column("locations", "email")
    op.drop_column("locations", "tel_number")
    op.drop_column("locations", "fax_number")
    op.drop_column("locations", "region")
    op.alter_column("organizations", "number", existing_type=sa.TEXT(), nullable=True)
    op.drop_column("organizations", "email")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organizations", sa.Column("email", sa.TEXT(), autoincrement=False, nullable=False)
    )
    op.alter_column("organizations", "number", existing_type=sa.TEXT(), nullable=False)
    op.add_column("locations", sa.Column("region", sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column(
        "locations", sa.Column("fax_number", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "locations", sa.Column("tel_number", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.add_column("locations", sa.Column("email", sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column("locations", sa.Column("name", sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column("locations", sa.Column("postcode", sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column(
        "locations", sa.Column("mobile_number", sa.TEXT(), autoincrement=False, nullable=False)
    )
    op.add_column("locations", sa.Column("street", sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
