"""update_date_time_columns

Revision ID: pkg_0007
Revises: pkg_0006
Create Date: 2026-09-28 16:58:24.009201

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "pkg_0007"
down_revision: str | Sequence[str] | None = "pkg_0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "audits",
        "valid_until",
        existing_type=sa.DATE(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.add_column(
        "user_invites", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_invites", "updated_at")
    op.alter_column(
        "audits",
        "valid_until",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DATE(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
