"""add_gtin

Revision ID: pkg_0003
Revises: pkg_0002
Create Date: 2026-07-08 17:41:02.286301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'pkg_0003'
down_revision: Union[str, Sequence[str], None] = 'pkg_0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_types', sa.Column('gtin', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset_types', 'gtin')
    # ### end Alembic commands ###
