"""add_gtin

Revision ID: pkg_0006
Revises: pkg_0005
Create Date: 2026-07-08 17:41:02.286301

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "pkg_0006"
down_revision: str | Sequence[str] | None = "pkg_0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("asset_types", sa.Column("gtin", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("asset_types", "gtin")
    # ### end Alembic commands ###
